# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3daae460922f91fef5bb42a0a58c4332c13824311d3e41dab343e36fde43abef0052b68d39c8b4c9322fcee021d5b2aae05f724bc24975ee3de00f3990ee34d7

test:
  secret_key_base: 5d18ad5e2ecadb5674957f3640350b801c7a3ddfc42e1356e3fb66db97835b8f264b1c2f2ec84ee50281a4f3cda0f16070caf8059a071982fd75bbe767d0f11b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
